# Estructuras algebraicas
## Conjuntos
Abordaremos los temas relacionados con la teoría de conjuntos desde una perspectiva intuitiva, más bien oparacional para abordar los conceptos básicos necesarios para desarrollar el resto de los capítulos.

### Definiciones Iniciales

Entenderemos por **conjunto** a una colección de objetos cualesquiera. Las palabras *conjunto, colecci\'on, familia* suelen ser usadas para denotar este objeto matemático. Los objetos que conforman un conjunto son llamados comunmente **elementos** (o **miembros**) del conjunto. Los conjuntos suelen denotarse con letras mayúsculas $A, B, C, P,\cdots$, mientras que los miembros que los conforman generalmente se denotan con letras minúsculas $a,b, x, y,\cdots$. Si $C$ es un conjunto y $x$ es un elemento de $C$, escribiremos $x\in C$ (o equivalentemente $C\ni x$) lo que se lee *$x$ pertenece al conjunto $C$*. Para denotar lo contrario usaremos el símbolo $\notin$, así $x\notin C$ significa que *$x$ no pertenece a $C$ o $x$ no es miembro de $C$*.

\smallskip

Puede ocurrir que elementos de un conjunto también pertenezcan a otro conjunto. En el caso que todo elemento de un conjunto $A$ es miembro del conjunto $C$ decimos que **$A$ es subconjunto de $C$** (o $C$ contiene a $A$), lo que denotaremos $A\subseteq C$. Es decir, si $x\in A$, entonces $x\in C$ para todo $x$, implica que $A\subseteq C$. Note que es posible que $A$ y $C$ tengan exactamente los mismos elementos, en este caso diremos que los conjuntos $A$ y $C$ son iguale y lo denotaremos por $A=C$. Sin embargo debemos comprobar que $A\subseteq C$ y $C\subseteq A$ para asegurar que $A=C$. En otro caso, cuando $A\subseteq C$ pero $A$ no es igual al conjunto $C$, diremos que **$A$ es un subconjunto propio de $C$** (o **$A$ está propiamente contenido en $C$**).

```{example}
El conjunto formado por 0, 1, 2, 3, 4, etc. es el llamado conjunto de los **números naturales** y se denota por $\mathbb{N}$.

Se debe saber que podemos definir un conjunto describiendo uno a uno sus miembros. Esto se hace encerrándolos entre llaves. Así, el conjunto de los números naturales es $\mathbb{N}=\{0, 1, 2, 3, 4,\cdots\}$.

Denotaremos por $\mathbb{N}^{*}=\{ 1, 2, 3, \cdots \}$.

```

```{example}
Dado el conjunto de los números enteros $\mathbb{Z}=\{\cdots,-3,-2,-1,0,1,2,3,\cdots \}$, el conjunto de los números pares (enteros pares) es el conjunto de los números de la forma $2k$ donde $k$ es un entero.
	
También se puede describir el conjunto anterior así: 
  
$$\{p\in\mathbb{Z}| p=2k \mbox{ para algún } k\in\mathbb{Z} \}$$ 
  
lo cual se lee: _el conjunto formado por todos los números enteros_ $p$ _tales que_ $p=2k$ _para algún número entero_ $k$.

```

```{example}
Denotaremos el conjunto de los números reales po $\mathbb{R}$. El conjunto de las soluciones de la ecuación $7x^{2}+4x-32=0$ es $C=\{x\in\mathbb{R}| x \mbox{ es solución de } 7x^{2}+4x-32=0 \}$.
  
```

### Operaciones entre conjuntos

Dados dos conjuntos $A$ y $B$ podemos definir nuevos conjuntos a partir de estos, con las operaciones entre conjuntos que definiremos a continuación.

```{definition,label="uniondeconjuntos"}
Dados dos conjuntos $A$ y $B$, el conjunto **unión** de $A$ y $B$ es el conjunto $A\cup B = \{ x| x\in A \mbox{ o } x\in B \}$.

``` 

Es decir, la unión de los conjuntos $A$ y $B$ es el conjunto formados por aquellos elementos que pertenezcan a al menos uno de los dos conjuntos, así un elemento que pertenezca tanto a $A$ como a $B$, es miembro de $A\cup B$.

```{definition, label="intersecciondeconjuntos"}
Dados dos conjuntos $A$ y $B$, el conjunto **intersección** de $A$ y $B$ es el conjunto $A\cap B = \{ x| x\in A \mbox{ y } x\in B \}$.

```

En otras palabras, la intersección de $A$ y $B$ es el conjunto formado por aquellos elementos que pertenecen a ambos conjuntos simultaneamente.

```{example}
Dados los conjuntos $A$ y $B$, tales que $B\subseteq A$ ($B$ es subconjunto de $A$).  Se tiene que $A\cup A=A$, más aún $A\cup B=A$. Además $A\cap A=A$ y $A\cap B=B$. 

```

```{example}
Sean $A=\{a,b,c\}$ y $B=\{c,d,e\}$. $A\cup B=\{a,b,c,d,e\}$ y $A\cap B=\{c\}$.

```

```{example}
Dado el conjunto de los números enteros, $\mathbb{Z}$. Los subconjuntos $\mathbb{Z}^{+}=\{p\in\mathbb{Z}| p \mbox{ es un entero positivo} \}$ y $\mathbb{Z}^{-}=\{p\in\mathbb{Z}| p \mbox{ es un entero negativo} \}$. Se tiene que $\mathbb{Z}\cap \mathbb{Z}^{+}=\mathbb{Z}^{+}$ y  $\mathbb{Z}\cup \mathbb{Z}^{-}=\mathbb{Z}$.

Ahora bien, pensemos en el conjunto $\mathbb{Z}^{+}\cap\mathbb{Z}^{-}$. Note que no existe nímero entero que pertenezca a $\mathbb{Z}^{+}$ y $\mathbb{Z}^{-}$ simultaneamente. Para que la intersección esté bien definida, el resultado debería ser un conjunto. Con ese fin daremos la siguiente definición.

```

```{definition, label="conjuntovacio"}
Diremos que un conjunto es **vacío** si no posee elementos y lo denotaremos por $\emptyset$.

```

```{remark}
El conjunto vacío es único. Basta con demostrar que dados dos conjuntos $\emptyset$ y $\emptyset_{1}$, se cumple que $\emptyset\subseteq \emptyset_{1}$ y $\emptyset_{1}\subseteq\emptyset$.

```

```{definition,label="conjuntodiferencia"}
Dados dos conjuntos $A$ y $B$, el **conjunto diferencia** $A-B$ es el conjunto $\{x\in A | x\notin B \}$.

```

```{example}
Dados los conjuntos de los números enteros, $\mathbb{Z}$ y el conjunto de los números naturales $\mathbb{N}=\{0,1,2,3,4,\cdots \}$, el conjunto diferencia $\mathbb{Z}-\mathbb{N}=\{p\in\mathbb{Z}| p\notin \mathbb{N} \}$ es decir, el conjunto de los números enteros que no son números naturales, que no es más que $\mathbb{Z}^{-}$.

```


*Generalización de unión e intersección*

Las operaciones entre conjuntos definidas antes consideran solo dos conjuntos, sin embargo podemos extender las nociones de unión e intesección de conjuntos a una cantidad cualquiera de conjuntos, finita o no.

Dado $n\in\mathbb{N}$. La unión de $n$ conjuntos $A_{1}, A_{2},\cdots,A_{n}$, puede definirse claramente a partir de la unión de dos conjuntos así:

i) Hallamos el conjunto unión de los primeros dos conjuntos $A_{1}\cup A_{2}$ (definición \@ref(def:uniondeconjuntos)).

ii) Ahora unimos el conjunto obtenido en el paso i. con el siguiente conjunto $A_{3}$, esto es $(A_{1}\cup A_{2})\cup A_{3}$.

iii) Repetimos el paso anterior hasta unir todos los conjuntos.

El algoritmo anterior nos muestra que es posible unir una cantidad finita cualquiera de conjuntos. Analogamente se pueden intersecctar $n$ conjuntos, siendo $n$ un número natural cualquiera.

Ahora bien, la unión e intersección de una cantidad arbitraria (no necesariamente finita) también se puede definir.

Dado $I$ un conjunto de índices. Una familia indexada por $I$ es una colección $\mathcal{F}=\{A_{\alpha} | \, \alpha\in I \}$. Note que esta definición permite que el conjunto $I$ sea cualquier conjunto, finito o infinito. Se suele usar el conjunto de los números enteros positivos como conjunto de índices (para numerar) pero se puede usar cualquier otro conjunto.

La **unión** de los conjuntos $A_{\alpha}$, con $\alpha\in I$, el el conjunto $\bigcup\mathcal{F}=\bigcup_{\alpha\in I} A_{\alpha}=\{x|\, x\in A_{\alpha} \mbox{ para algún } \alpha\in I \}$. De forma análoga, la **intersección** de los conjuntos $A_{\alpha}$, con $\alpha\in I$, es el conjunto $\bigcap A_{\alpha}=\{x|\, x\in A_{\alpha} \mbox{ para todo } \alpha\in I \}$. Vale resaltar que cuando $I$ es un conjunto finito, digamos $I=\{1,2,\cdots, n\}$, se tiene que $\bigcup A_{\alpha}=\{x|\, x\in A_{\alpha} \mbox{ para algún } \alpha\in I \}=\{x|\, x\in A_{1} \mbox{ o } x\in A_{2}\mbox{ o }\cdots \mbox{ o } x\in A_{n} \}=A_{1}\cup A_{2},\cdots , A_{n}$.

### Producto cartesiano

```{definition}
Dados $a$ y $b$ miembros de los conjuntos $A$ y $B$ respectivamente, llamaremos *par ordenado al arreglo $(a,b)$. Diremos que dos pares ordenados $(a,b)$ y $(c,d)$ son iguales (es decir $(a,b)=(c,d)$ si y solo si $a=c$ y $b=d$.
```

```{definition}
Sean $A$ y $B$ dos conjuntos. El *producto cartesiano de $A$ y $B$* es el conjunto $A\times B$ formado por todos los pares ordenados $(a,b)$, donde $a\in A$ y $b\in B$. Es decir $A\times B=\{(a,b)| \, a\in A \mbox{ y } b\in B \}$.

```

```{example}
Si $A=\{1,2,3\}$ y $B=\{3,4,5\}$, entonces el producto cartesiano de $A$ y $B$ es el conjunto

$A\times B=\{ (1,3), (1,4), (1,5), (2,3), (2,4), (2,5), (3,3), (3,4), (3,5)\}$.

```

```{remark}
Dados los conjuntos $A$ y $B$, podemos considerar los conjuntos $A\times B$ y $B\times A$. Como conjuntos son distintos, aunque existe una relación entre ellos (se discutirá mas adelante cuando se definan correspondencias biyectivas ). De igual forma se puede definir el producto cartesiano de una cantidad finita de conjuntos (de forma análoga a la unión de conjuntos). Si $A$, $B$ y $C$ son conjuntos, podemos definir el conjunto $A\times B\times C$ formado por los arreglos (terna ordenada) del tipo $(a,b,c)$, donde $a\in A$, $b\in B$ y $c\in C$. Más aun, se puede definir el producto cartesiano para una cantidad arbitraria de conjuntos. Dado un conjunto de índices $I$, el producto cartesiano de una familia indexada por $I$, $\mathcal{F}=\{A_{\alpha}|\, \alpha\in I \}$, es el conjunto de aplicaciones $f:I\longrightarrow \bigcup\mathcal{F} \mbox{ tales que } f(\alpha)\in A_{\alpha}$, es decir $\prod_{\alpha \in I} A_{\alpha}=\{f:I\longrightarrow\bigcup \mathcal{F} |\, f(\alpha)\in A_{\alpha} \}$. Por último, queremos recalcar que es posible hacer el producto cartesiano de un conjunto consigo mismo, esto es $A\times A$ formado, como es natural por los pares $(a,b)$, con  $a$ y $b$ elementos de $A$. En este caso se puede denotar $A^{2}$ al producto cartesiano de $A$ consigo mismo (y se denota $A^{n}$ al producto cartesiano de $A$ consigo mismo $n$ veces). Para $A^{2}$ llamamos **diagonal** al conjunto formado por los pares de la forma $(a,a)$ y se denota por $\Delta$, es decir, $\Delta=\{(a,a)|\, a\in A \}$.

```

## Relaciones de Equivalencia

\smallskip

```{definition}
Dados dos conjuntos $A$ y $B$, una **relación de $A$ sobre $B$**, es un subconjunto $R$ del producto cartesiano $A\times B$. En el caso que $R\subseteq A\times A$, se dice que $R$ es una relación sobre $A$.

```

```{definition}
Dada un relación $R$ sobre un conjunto no vacío $A$. Decimos que:

i) $R$ es **reflexiva** si para todo $a\in A$, se tiene que $(a,a)\in R$ (es decir, la diagonal $\Delta$ es subconjunto de $R$).

ii) $R$ es **simétrica** si para todo $a,b \in A$, se cumple que: $(a,b)\in R \Leftrightarrow  (b,a)\in R$.

iii) $R$ es **transitiva** si para todo $a,b, c \in A$, se cumple que: $(a,b)\in R$ y  $(b,c)\in R$ $\Rightarrow (a,c)\in R$.

```

```{definition}
Una relación $R$ sobre un conjunto no vacío $A$, que es reflexiva, simétrica y transitiva, se dice **de equivalencia**.
```

```{remark}
Si $R$ es una relación sobre $A$, el hecho de que $(a,b)\in R$ se puede denotar como $aRb$ o como $a\simeq b$ cuando el contexto lo permita y quede claro cual es la relación.
De este modo, $R$ es una relación de equivalencia si para todo $a,b,c\in A$ se tiene que: 
  
i) $aRa$,

ii) $aRb\Leftrightarrow bRa$ y 

iii) $aRb$ y $bRc\Rightarrow aRc$.

```

```{example, label="ejm1-9"}
**La igualdad** es una relación de equivalencia.
Dado el conjunto de los números reales $\mathbb{R}$, la igualdad es la relación $aRb$ siempre que $a$ y $b$ sean el mismo número real y se denota por $a=b$. Es claramente reflexiva ya que $a=a$; simétrica pues $a=b$ implica que $a$ y $b$ son el mismo número real y por lo tanto $b=a$ y es transitiva ya que si $a=b$ y $b=a$, entonces $a,b$ y $c$ son el mismo número real, lo que implica que $a=c$.
Note que el conjunto donde definimos la igualdad (los reales $\mathbb{R}$) es irrelevante. Esta relación puede (y de hecho está) definida sobre cualquien conjunto.

```
	
```{example, label="ejm1-10"}
Dado el conjunto de los números enteros $\mathbb{Z}$, definamos la siguiente relación $R$: $(a,b)\in R$ si y solo si $b-a$ es un número par (o lo que es igual, es un múltiplo de $2$).
$R$ es una relación reflexiva, ya que $a-a=0$ y cero es múltiplo de $2$. Es simétrica ya que si $b-a$ es un número par, entonces $a-b$ también lo es. Ahora mostremos que es transitiva, sean $a, b$ y $c$ números enteros tales que $(a,b)\in R$ y $(b,c)\in R$, entonces $b-a$ y $c-b$ son números pares como también su suma $c-a=(c-b)+(b-a)$, por lo tanto $(a,c)\in R$. En consecuencia, $R$ es una relación de equivalencia.

```

```{example, label="ejm1-11"}
**La congruencia modular**. Definiremos la siguiente relación sobre el conjunto de los números enteros, $\mathbb{Z}$. Dado un número natural $n$, para cuales quiera enteros $a$ y $b$, decimos que $aRb$ si y solo si $b-a$ es divisible por $n$ (o equivalentemente, $b-a$ es múltiplo de $n$); lo denotamos por $a\cong b\mbox{ mod } n$ y se lee *$a$ congruente con $b$ módulo $n$*.
Es fácil demostrar que la relación es reflexiva.
Supongamos que $a\cong b \mbox{ mod } n$, entonces $b-a=kn$ para algún $k\in\mathbb{Z}$. Luego, $a-b=-kn$ por lo tanto $b\cong a \mbox{ mod } n$. Entonces la relación es simétrica.
Ahora supongamos que $a\cong b \mbox{ mod } n$ y $b\cong c \mbox{ mod } n$. Se tiene así que existen $k,q\in\mathbb{Z}$ tales que $b-a=kn$ y $c-b=qn$. De este modo $c-a=(c-b)+(b-a)=(q-k)n$, de donde se sigue que $a\cong c \mbox{ mod } n$.
De lo anterior se sigue que la relación de congruencia módulo $n$ es una relación de equivalencia.

```

```{definition}
Dados una relación de equivalencia $R$ sobre un conjunto $A$ y $a\in A$. Definimos **la clase de equivalencia de $a$** como el conjunto $[a]=\{b\in A | aRb\}$. También se denota por $cl(a)$ o $\tilde{a}$.

```

Pensemos en las clases de equivalencias de los ejemplos anteriores. La clase de equivalencia de $a$ para la relación *igualdad* \@ref(exm:ejm1-9) es el conjunto cuyo único elemento es $a$. Mientras que en el ejemplo \@ref(exm:ejm1-10), la relación solo define dos clases de equivalencia, el conjunto de los números enteros pares y el conjunto de los números enteros impares. En el caso de la *congruencia módulo $n$* \@ref(exm:ejm1-11), la clase de equivalencia de un entero $a$ es el conjunto $\{b\in\mathbb{Z}| a\cong b\mbox{ mod } n \}=\{b\in\mathbb{Z}| b-a=kn\mbox{ para algún } k\in\mathbb{Z} \}=\{b\in\mathbb{Z}| b=kn+a\mbox{ para algún } k\in\mathbb{Z} \}$ es decir, todos los enteros $b$ que tienen por resto $a$ al ser divididos por $n$.


```{definition}
Dado un conjunto $A$, **una partición de $A$** es una colección de subconjuntos no vacíos de $A$, disjuntos dos a dos, tales que la unión de ellos es todo $A$. Es decir, $\{ B_{i}\subseteq A |\,, i\in I\}$, donde $I$ es un conjunto de índices y se tiene que: 
  
i)  $B_{i}\neq\emptyset$ para todo $i\in I$.

ii) $B_{i}\neq B_{j}$, para $i,j\in I$ y $i\neq j$.

iii) $\bigcup_{i\in I} B_{i}=A$.
	
Cada subconjunto $B_{i}$ es una parte de $A$.

```


```{theorem}
Las clases de equivalencia definidas por una relación de equivalencia sobre un conjunto $A$ definen una partición de $A$. Recíprocamente, una partición de un conjunto $A$, induce una relación de equivalencia sobre $A$ de forma que las clases de equivalencia corresponden a las partes de la partición.

```

```{proof}
Sea $R$ una clase de equivalencia sobre $A$. Por la reflexividad de $R$ se tiene que $a\in[a]$, por lo tanto $\bigcup_{a\in A} [a]= A$ y $[a]$ es no vacío. Supongamos que $[a]\cap [b]\neq\emptyset$, entonces existe $c\in A$ tal que $c\in [a]\cap [b]$, por transitividad, $aRb$, por lo tanto $[a]=[b]$, es decir, si dos clases no son disjuntas, son iguales.
Recíprocamente, sea  $\{ B_{i}\subseteq A |\,, i\in I\}$ una partición. Definimos la relación $R$, sobre $A$, así: para $a,b\in A$, $aRb$ si y solo si existe $i\in I$ tal que $a,b\in B_{i}$, esto es, $a$ y $b$ pertenecen a la misma parte $B_{i}$. Es muy fácil ver que esta relación es de equivalencia.

```

## Funciones

Veamos ahora la definición de función (o aplicación), concepto importantísimo en toda la matemática y bastante conocido y usado en la educación matemáticas desde los niveles más básicos. Digamos que una *función* es una regla de asignación entre conjuntos, por ejemplo la función  que asigna a cada número real $r$ su parte entera $\lVert n \rVert$ (el mayor entero menor o igual que $r$), es una función del conjunto de los números reales $\mathbb{R}$ al conjunto de los números enteros y su regla de asignación es la antes descrita. La relación $y=x^{2}$, es una función de $\mathbb{R}$ en si mismo que a cada número real $x$ le relaciona su cuadrado $x^{2}$, desde otro punto de vista, los pares $(x,y)$ pertenecen a la función si $y=x^{2}$, dicho de otro modo, los pares $(x,x^{2})$ forman parte de la función.

```{definition}
Dados dos conjuntos no vacíos $A$ y $B$, una **función de $A$ en $B$** es un subconjunto $G$ de $A\times B$ tal que para cada $a\in A$, existe un único $b\in B$, tal que $(a,b)\in G$. Lo denotamos por $f: A\longrightarrow B$, con $f(a)=b$. Llamaremos **dominio de $f$** al conjunto $A$ (y se denota $dom(f$) y **codominio** al conjunto $B$. También se suelen llamar conjunto de partida y conjunto de llegada respectivamente.
                                          
```

```{example, label="identidad"}
Dado un conjunto $A$ no vacío, la **función identidad** es aquella que a cada $a$, le asigna el mismo elemento $a$. Esto es, $i: A\longrightarrow A$ definida por $i(a)=a$ para todo $a\in A$, que no es más que la diagonal de $A\times A$.

```

```{example, label="ejm1-12"}
Sea $f: \mathbb{R}\longrightarrow\mathbb{R}$ definida por $f(x)=x^{2}$. Los pares de la forma $(x,x^{2})$ forman parte de la función. El conjunto $dom(f)=\mathbb{R}$ y su codominio es $\mathbb{R}$.

```

```{example, label="ejm1-13"}
Dados $\mathbb{Z}$ el conjunto de los números enteros, y $\mathbb{Q}$ el conjunto de los números racionales, definimos $f:\mathbb{Z}\times\mathbb{Z}\longrightarrow\mathbb{Q}$ de la siguiente forma $f((m,n))=\frac{m}{n}$.

```

```{example, label="ejm1-14"}
Dados $\mathbb{Z}$ el conjunto de los números enteros, y $\mathbb{Q}$ el conjunto de los números racionales, definimos $f:\mathbb{Q}\longrightarrow \mathbb{Z}\times\mathbb{Z}$ de la siguiente forma. Dado un número racional $q\in\mathbb{Q}$, existen enteros sin factores comunes $m$ y $n$ tales que $q=\frac{m}{n}$. Así, $f(q)=(m,n)$.

```

```{example, label="ejm1-15"}
Sean $A$ y $B$ conjuntos no vacíos tales que $A\subseteq B$, $\imath: A \longrightarrow B$ dada por $\imath(a)=a$ es la función \textit{inclusión de $A$ en $B$}.

```

```{example, label="ejm1-16"}
Sea $C$ el conjunto $\{a,b,c\}$. Podemos definir la siguiente función $f:C\longrightarrow C$, donde $f(a)=b$, $f(b)=c$ y $f(c)=a$.

```

```{example, label="ejm1-17"}
Sean $A$ y $B$ conjuntos no vacíos. $\pi: A\times B\longrightarrow A$ dada por $\pi((a,b))=a$ es la función \textit{proyección de $A\times B$ sobre $A$}. Se puede definir de forma análoga la proyección sobre $B$.

```

```{example, label="ejm1-18"}
Dado un conjunto $C$ sobre el cual está definida una relación de equivalencia $R$. Llamaremos **conjunto cociente** al conjunto de las clases de equivalencia definidas por $R$, esto es $C/R=\{[a] | a\in C \}$. Definimos $f:C\longrightarrow C/R$, como $f(a)=[a]$.

```

```{definition}
Una función $f:A\longrightarrow B$ se dice **sobreyectiva** si para todo $b\in B$, existe $a\in A$ tal que $f(a)=b$.

```

Otra forma de entender la sobreyectividad es pensar que la función "cubre" todo el conjunto de llegada (el codominio).
También podemos entenderla en términos de la imagen de la función, que definiremos a continuación: dada $f:A\longrightarrow B$, si $C\subseteq A$, definimos la **imagen de un conjunto $C$** como el conjunto $\{f(a) | a\in C \}$, al cual denotamos por $f[C]$ o $f''C$. El conjunto imagen del dominio se llamará **Imagen de $f$** a secas, este es $f[A]$ y también se denota $Img(f)$. Entonces la  sobreyectividad es equivalente a que la imagen de $f$ sea igual al codominio, es decir $f[A]=B$.

```{definition}
Una función $f:A\longrightarrow B$ se llamará **inyectiva** si para todo $a\mbox{ y }b\in A$, si $a\neq b$, entonces $f(a)\neq f(b)$.

```

Un función inyectiva es pues una función que a cada elemento del dominio le asocia elementos distintos del codominio. Para entender mejor esta definición, definiremos imagen inversa: dada $f:A\longrightarrow B$, si $C\subseteq B$, definimos la **imagen inversa de un conjunto $C$** como el conjunto $\{a | f(a)\in C \}$ y se denota por $f^{-1}[C]$. De este modo, una función es inyectiva si la imagen inversa de los subconjuntos unitarios del codominio tienen a lo sumo un elemento, es decir, $f^{-1}[\{b\}]$ tiene un elemento o es vacío, para todo $b\in B$.

En los ejemplos que antes vimos, la función identidad es sobreyectiva e inyectiva, es decir **biyectiva** (cuando una función es inyectiva y sobreyectiva se le llama biyectiva). La función del ejemplo \@ref(exm:ejm1-12) no es inyectiva, basta ver que $f(1)=f(-1)$. Tampoco es sobreyectiva, no existe número real que tenga un cuadrado negativo. Los ejemplos \@ref(exm:ejm1-15) y \@ref(exm:ejm1-16) muestran funciones biyectivas. Pero los ejemplos \@ref(exm:ejm1-13) y \@ref(exm:ejm1-18) son funciones sobreyectivas que no son inyectivas, mientras que el ejemplo \@ref(exm:ejm1-15) muestra una función inyectiva que no es sobreyectiva.

A continuación definirimos cuando dos funciones son iguales. Intiutivamente, dos funciones serán iguales cuando expresen la misma regla de asignación sobre los mismos objetos. En seguida la definición formal:

```{definition}
Dos funciones $f$ y $g$ de $A$ en $B$, se dicen que son **iguales** si $f(a)=g(a)$ para todo $a\in A$.

```

Podemos también plantear la situación en la que se relacionen los elementos de dos conjuntos pasando por un tercer conjunto haciendo uso de dos funciones. Es decir, una regla de asignación entre los elementos de un conjunto $A$, en otro conjunto $B$, y otra regla que relacione a los elementos de $B$ con un conjunto $C$ se pueden componer para obtener una regla (una función) de $A$ a $C$.

```{definition}
Sean $f:A\longrightarrow B$ y $g:B\longrightarrow C$ dos funciones. La composición de $f$ y $g$ es una función de $A$ en $B$ que asigna a cada $a\in A$ el elemento $g(f(a))\in C$. Se denota por $g\circ f$. Entonces $g\circ f: A\longrightarrow B$, definido por $(g\circ f)(a)=g(f(a))$.

```

```{remark}
Note que el dominio de la función $g$ (la segunda en ser aplicada) debe ser igual al codominio de la función $f$ (pudiése ser un subconjunto del codominio).

Es importante el orden de las funciones, en el contexto general descrito en la definición, no tiene sentido pensar en la composición $f\circ g$, ya que $g(b)$ es un elemento del conjunto $C$ que no es el dominio de $f$, por lo tanto la expresión $f(g(b))$ carece de sentido, salvo que $B$ sea subconjunto de $A$.

```

```{example}
Sea $A=\{a,b,c\}$. Sean $f:A\longrightarrow A$ y $g:A\longrightarrow A$ funciones definida por $f(a)=b$, $f(b)=c$ y $f(c)=a$ y $g(a)=a$, $g(b)=c$ y $g(c)=b$. Entonces $(g\circ f)(a)=g(f(a))=g(b)=c$, $(g\circ f)(b)=g(f(b))=g(c)=b$ y $(g\circ f)(c)=g(f(c))=g(a)=a$. Análogamente,  $(f\circ g)(a)=b$, $(f\circ g)(b)=a$ y $(f\circ g)(c)=c$. Aunque ambas funciones compuestas, $g\circ f$ y $f\circ g$ son funciones de $A$ en si mismo, no son iguales ya que  $(g\circ f)(a)=c$ y $(f\circ g)(a)=b$, es decir $(g\circ f)(a)\neq (f\circ g)(a)$
  
```

```{example}
Sea $A=\{a,b,c\}$. Sean $f:A\longrightarrow A$ y $g:A\longrightarrow A$ funciones definida por $f(a)=b$, $f(b)=c$ y $f(c)=a$ y $g(b)=a$, $g(c)=b$ y $g(a)=c$. Entonces $g\circ f$  (y $f\circ g$) es la función identidad de $A$.

```

```{example}
Dadas las siguientes funciones $f:\mathbb{R}\longrightarrow \mathbb{Z}:x\longmapsto \lVert x\rVert$, la notación que sigue de los dos puntos, $x\longmapsto \lVert x\rVert$ nos indica la regla de asignación, esto es $f(x)=\lVert x\rVert$, donde $\lVert x\rVert$ denota la \textit{parte entera} del número real $x$, a saber: \textit{el mayor entero menor o igual a $x$}. Y la función $g:\mathbb{Z}\longrightarrow \{0,e\}$, definida por 

\begin{equation}
	g(p) = \left\{
	\begin{array}{ll}
	0      & \mbox{ si } p \mbox{ es un número par } \\
	e      & \mbox{ si } p \mbox{ es un número impar }
 \end{array}
	\right.
\end{equation}
	
Entonces, la función $g\circ f$ aplica números reales en $\{0,e\}$. Sin embargo $f\circ g$ no puede definirse, ya que el codominio de $g$ no es un subconjunto del dominio de $f$.
	
Calculemos $g\circ f$ para algunos números: $(g\circ f)(\frac{1}{2})=g(\lVert \frac{1}{2} \rVert)=g(0)=0$, $(g\circ f)(\frac{-3}{2})=g(\lVert \frac{-3}{2} \rVert)=g(-2)=0$ y $(g\circ f)(\pi)=g(\lVert \pi \rVert)=g(3)=e$.

```

Al igual que se pueden componer dos funciones, $f$ y $g$, también se puede hacer con una cantidad cualquiera (finita) de funciones. Dadas las funciones  $f:A\longrightarrow B$, $g:B\longrightarrow C$ y $h:\longrightarrow D$, podemos componer $f$ y $g$ y obtener una función de $A$ en $C$. Y a su vez, componer esta función (la compuesta $g\circ f$ de $A$ en $C$) con la función $h$ y así obtener $h\circ (g\circ f)$ de $A$ en $D$, que es la compuesta de las tres funciones.  En este caso cabe preguntarse si es igual $h\circ (g\circ f)$ que $(h\circ g)\circ f$. El siguiente resultado contesta esta pregunta.

```{lemma}
Sean $f:A\longrightarrow B$, $g:B\longrightarrow C$ y $h:\longrightarrow D$ funciones. Entonces $h\circ (g\circ f)=(h\circ g)\circ f$.

```

```{proof}
Lo primero que debemos notar es que tanto $h\circ (g\circ f)$ como $(h\circ g)\circ f$ tienen el mismo dominio y codominio. Efectivamente, $h\circ (g\circ f)$ tiene por dominio el conjunto $A$, porque es dominio de $g\circ f$ (ya vimos antes que el dominio y el codominio de $g\circ f$ son el dominio de $f$ y el codominio de $g$ respectivamente), y su codominio es $D$, el codominio de $h$. Del mismo modo $(h\circ g)\circ f$ tiene dominio $A$ (al ser $dom(f)=A$) y codominio $D$ (que es el codominio de $h\circ g$).
Ahora demostremos que para cada $a\in A$, $(h\circ (g\circ f))(a)=((h\circ g)\circ f)(a)$. Y es muy fácil de ver, $$(h\circ (g\circ f))(a)=h(g\circ f)(a)=h(g(f(a)))=(h\circ g)(f(a))=((h\circ g)\circ f)(a)$$ lo que demuestra lo que queríamos.

```

Qué sucederá con la composición de dos funciones inyectivas, o sobreyectivas. Esto se muestra en este resultado:

```{lemma, label="lema1-2"}
Sean $f:A\longrightarrow B$ y $g:B\longrightarrow C$ dos funciones. Entonces:
  
1) $g\circ f$ es sobreyectiva si $f$ y $g$ lo son.

2) $g\circ f$ es inyectiva si $f$ y $g$ lo son.

```

```{proof}

1) Supongamos que $f$ y $g$ son funciones sobreyectivas. Sea $c\in C$, como $g$ es sobreyectiva, existe $b\in B$ tal que $c=g(b)$. Y como $f$ es sobreyectiva, existe $a\in A$ tal que $b=f(a)$. Se tiene que dado $c$ existe $a$ tal que $c=g(b)=g(f(a))=(g\circ f)(a)$, por lo tanto $g\circ f$ es sobreyectiva.

2) Supongamos que $f$ y $g$ son funciones inyectivas. Sean $a_{1}, a_{2}\in A$, tales que $a_{1}\neq a_{2}$. Como $f$ es inyectiva, se tiene que $f(a_{1})\neq f(a_{2})$. Ahora, como $f(a_{1}) \mbox{ y }f(a_{2})\in B$ y $f(a_{1})\neq f(a_{2})$, de la inyectividad de $g$ se sigue que $g(f(a_{1}))\neq g(f(a_{2}))$, es decir, $(g\circ f)(a_{1})\neq (g\circ f)(a_{2})$, por lo tanto $g\circ f$ es inyectiva.

```

Si una función $f$ de $A$ en $B$ es biyectiva, para cada $b\in B$ existe $a\in A$ tal que $f(a)=b$, y de la inyectividad se tiene que $a$ es único. De esta manera se puede definir una nueva función de $B$ en $A$ que guarda una extrecha relación con $f$ (pues se define a partir de ella). Dicha función es la **inversa** de $f$. Definámosla formalmente.

```{definition}
Dada una función biyectiva $f: A \longrightarrow B$, la \textit{función inversa de $f$} es la función $f^{-1}$, definida así $f^{-1}(b)=a$ si y solo si $f(a)=b$.

```

Además, para cada $a\in A$, sea $b=f(a)$, de donde $(f^{-1}\circ f)(a)=f^{-1}(f(a))=f^{-1}(b)=a$. Es decir, $f^{-1}\circ f$ es la identidad de $A$ (en sí mismo). Análogamente se puede probar que $f\circ f^{-1}$ es la identidad de $B$. Esto es la demostración del siguiente resultado.

```{lemma}
Dada una función $f:A\longrightarrow B$ biyectiva, las funciones $f^{-1}\circ f$ y $f\circ f^{-1}$ son iguales a la función identidad (correspondiente a los conjuntos $A$ y $B$).

```

Recíprocamente, si dada una función $f: A\longrightarrow B$, existe una función $g:B\longrightarrow A$ tal que $g\circ f$ y $f\circ g$ son la función identidad (sobre $A$ y $B$ respectivamente), entonces se tiene que $f$ es sobreyectiva, en efecto, dado $b\in B$, $b=(f\circ g)(b)$, ya que $f\circ g$ es la identidad (sobre $B$) por lo tanto $b=f(g(b))=f(a)$ para algún $a\in A$ (donde $a=g(b)$). Observemos también que $f$ es inyectiva, ya que si $f(a_{1})=f(a_{2})$ se tiene que $g(f(a_{1}))=g(f(a_{2}))$, como $g\circ f$ es la identidad (sobre $A$) se tiene que $a_{1}=a_{2}$. Esto se puede expresar como sigue.

```{lemma}
La función $f:A\longrightarrow B$ es biyectiva si y solo si existe una función $g:B\longrightarrow A$ tal que $g\circ f$ y $f\circ g$ son la función identidad sobre $A$ y $B$ respectivamente.

```

```{definition}
Sea $C$ un conjunto no vacío. $\mathcal{A}(C)$ es el conjunto de todas las funciones biyectivas de $C$ sobre sí mismo.

```

Respecto a este conjunto, si consideramos la operación *composición de funciones*, tenemos que $\mathcal{A}(C)$ es cerrado bajo esta operación, esto lo demostramos ya en el lema \@ref(lem=lema1-2). Además, como vimos antes, la composición de funciones es asociativa. Sabemos que la identidad y la función inversa son funciones biyectivas (pertenecen también al conjunto $\mathcal{A}(C)$). Es decir, tenemos un conjunto ($\mathcal{A}(C)$) con una operación (la composición de funciones) que tiene una estructura especial (la de grupo). Profundizaremos en esto en la siguiente sección.

## Cardinales

En esta sección demostraremos solo algunos resultados referidos a cardinalidad y números cardinales, solo aquellos que nos sean realmente útiles para el tema que nos ocupa en este trabajo. Quien desee ver las otras demostraciones y ahondar en este tema puede referirse a <añadir bibliografia...Kunen>.

```{definition}
Dos conjuntos $A, B$ son equipotentes si existe una biyección $f:A \longrightarrow B$ y se denota por $A\sim B$.

```

```{theorem, label="teo1-2"}
La equipotencia es una relación de equivalencia.

```

Podemos preguntarnos cuántos elementos tiene un conjunto. Una forma de "contar" los elementos que tiene un conjunto es la siguiente: Sean $A_{0}=\emptyset$ y para cada número natural $n$, sea $A_{n}=\{1,2,..., n\}$. Es fácil ver que $A_{n}=A_{m}$ si y solo si $n=m$ \@ref(exr:ejc1). De este modo, para ver que un conjunto $C$ tiene $n$ elementos basta ver que es equipotente con $A_{n}$, es decir $C\sim A_{n}$. Diremos que un conjunto es **finito** si es equipotente con algún $A_{n}$ para algún $n\in\mathbb{N}$. Si un conjunto no es finito diremos que es **infinito**. 

Lo anterior nos da una idea del concepto de cardinalidad, que formalmente se definiría como sigue.

```{definition}
Dado un conjunto $C$, la clase de equivalencia definida por la relación de equipotencia se conoce como el **cardinal** (o **cardinalidad** o **número cardinal**) de $C$ y se denota por $|C|$.

```

En algunos libros pueden conseguirse otras definiciones de cardinalidad. Los números cardinales pueden ser definidos mas formalmente como un objeto matemático y son de gran importancia en teoría de conjuntos, teniendo ellos mismos una importancia intrínseca, Sin embargo, la definición que presentamos se adecua perfectamente a los temas que trabajaremos aquí.
De la definición anterior y el teorema \@ref(thm:teo1-2) podemos ver los cardinales tienen las siguientes propiedades:

i) Todo conjunto tiene un único número cardinal.
ii) Dos conjuntos tienen el mismo número cardinal si y solo si son equipotentes.
iii) El cardinal de un conjunto finito es la cantidad de elementos que lo conforman.

```{example}
La cardinalidad de los conjuntos $A_{n}$ definidos antes es $n$ (la cantidad de elementos que tiene el conjunto).
La cardinalidad del conjunto de los números naturales es $\aleph_{0}$ (se lee alef cero) (también puede conseguirse en alguna literatura que $|\mathbb{N}|=\omega$ y así el primer cardinal infinito $\aleph_{0}$, es igual el ordinal omega). Cualquier conjunto de cardinalidad $\aleph_{0}$, se dice **numerable**. Si un conjunto no es numerable, diremos que es un conjunto **no numerable**.
El número cardinal del conjunto de los números enteros $\mathbb{Z}$ es $\aleph_{0}$, por lo tanto es un conjunto numerable, al igual que el conjunto de los números racionales $\mathbb{Q}$. Por otro lado, el conjunto de los números reales no es numerable.

```


```{remark}
La cardinalidad del producto cartesiano de dos conjuntos $A, B$ es el producto  $|A||B|$.

```

### Ejercicios

```{exercise, label="ejc1"}
Dados los conjuntos $A_{0}=\emptyset$ y para cada número natural $n$, sea $A_{n}=\{1,2,..., n\}$. Demuestre que $A_{n}=A_{m}$ si y solo si $n=m$.

Supongamos que $A_{n}=A_{m}$, entonces es fácil ver que $n=M$ (en caso contrario se tendría que $n<m$ o $n>m$). Recíprocamente, si $n=m$, por definición es claro que $A_{n}\subseteq A_{m}$ y $A_{m}\subseteq A_{n}$.

```

```{exercise, label="ejc2"}
Denuestre que los conjuntos $\mathbb{Z}$, $\mathbb{Q}$ son conjuntos numerables.

Basta probar que $\mathbb{Z}\sim \mathbb{N}$ y $\mathbb{Q}\sim \mathbb{N}$. Para esto debemos hallar biyecciones entre los conjuntos. Sea $f:\mathbb{Z}\longrightarrow \mathbb{N}$ definida así: 
  $$f(n) = \left\{
	\begin{array}{ll}
	-2n-1      & \mbox{ si } n<0\\
	2n      & \mbox{ si } n>=0
	\end{array}
	\right.$$
Es fácil ver que $f$ es una biyección, ya que $f$ asigna cada número entero negativo a los números naturales impares (1, 3, 5, ...) y cada número entero positivo a los números naturales pares (0, 2, 4, ...).
```

## Teoría de Grupos

En esta sección estudiaremos un objeto matemático de gran importancia, los grupos. En la sección anterior vimos un grupo que surgió de manera natural, $\mathcal{C}$ junto a la operación composición de funciones, pero el grupo más familiar es el de los números enteros (con la operación suma), con el que nos topamos desde la infancia; en ambos ejemplos vemos que la operación es asociativa, tiene un elemento neutro (la función identidad en el primer caso y el número cero en el caso de los números naturales) y un elemento inverso (la función inversa en un caso y el opuesto en el caso de los naturales).

A continuación presentaremos la definición formal de grupo así como un amplio repertorio de resultados bien conocidos en álgebra respecto a este objeto.

Dado un conjunto no vacío $G$, una *operación binaria* es una función $G\times G\longrightarrow G$. Comunmente se usan las notaciones $a\ast b$ o  $a\cdot b$ para denotar la imagen de $(a,b)$ por la función, aunque puede también usarse $ab$ (obviando el punto como se hace para expresar el producto de dos números) o incluso $a+b$ cuando la operación es la suma usual (como sucede con los números enteros).

```{definition}
Un par $(G,\ast)$, donde $G$ es un conjunto no vacío y una operacón binaria $\ast:G\times G\longrightarrow G$, forman un **grupo** si:
  
i) Para todo $a,b,c\in G$, $(a\ast b)\ast c=a\ast (b\ast c)$. Es decir, la operación es *asociativa*.
		
ii) Existe un elemento $e\in G$ tal que $a\ast e=e\ast a=a$. Llamaremos a tal elemento *neutro (o identidad) bilateral* de $G$.
		
iii) Para todo $a\in G$, existe un elemento $a^{-1}\in G$ tal que $a^{-1}\ast a=a\ast a^{-1}=e$, llamado *inverso* de $a$.

```

```{remark}
Puede hacerse referencia al grupo nombrando solo el conjunto $G$ cuando quede claro cual es la operación.
Si una operacón binaria $\ast:G\times G\longrightarrow G$ es asociativa (i.), se dice que $(G,\ast)$ es un *semigrupo*. Un **monoide** es un semigrupo con identidad (ii.). De este modo, se puede decir que un grupo es un monoide con inverso (bilateral).

```

Un semigrupo $G$ se llamará **abeliano** o **commutativo** si la operación es

iv) Commutativa, es decir, $a*b=b*a$, para todo $a, b\in G$.
   
El **orden** de un grupo $G$ es la cantidad de elementos que tiene el grupo, es decir, la cardinalidad de $G$ ($|G|$). También se denota $o(G)$ Decimos que un grupo es de **orden finito** (o simplemente finito) si $|G|$ es finito. En caso contrario decimos que el grupo es **infinito**.

```{example}
Como ya lo hemos mencionado, el conjunto de los números enteros, $\mathbb{Z}$ con la operación suma (la suma usual de enteros), forman un grupo. El lector podrá verificar fácilmente que la operación suma es cerrada, es asociativa, que el cero es el elemento neutro ($e$ en la definición) y que cada elemento tiene un inverso ($a^{-1}=-a$). Además es claro que se trata de un grupo abeliano (la suma es una operación commutativa).

```

```{example}
Dado el conjunto $G={1,-1}$. Definimos la operación $\ast:G\times G \longrightarrow G$ como el producto de números reales usual. El par $(G,\ast)$ forman un grupo abeliano de orden $2$.

```

```{example}
El conjunto de los números racionales $\mathbb{Q}$ con la suma usual, es un grupo abeliano.

```

```{example}
Consideremos un cuadrado cuyos vértices estan numerados consecutivamente $1,2,3,4$ centrado en el origen del palno cartesiano y de lados paralelos a los ejes coordenados.

Sea $C_{4}$ el conjunto formado por las siguientes transformaciones: $R$, una rotación de $90º$ del cuadrado. $R^{2}$ una rotación de $180º$ del cuadrados. $R^{3}$ una rotación de $270º$ del cuadrado (todas en el sentido de las agujas del reloj, centradas en el origen). $I$, una rotación de $360º$ (igual que antes en sentido horario, centrada en el origen). $T_{x}$ y $T_{y}$, reflexiones sobre los ejes $x$ y $y$ respectivamente y $T_{I}$ y $T_{II}$ reflexiones sobre las diagonales que pasan por los vértices que están en el primer y tercer cuadrante (la primera) y en el segundo y cuarto cuadrante (la segunda). Con la operación *composición de funciones*, el conjunto $C_{4} = {R, R^{2}, R^{3}, I, T_{x}, T_{y}, T_{I}, T_{II}}$ es un grupo no abeliano de orden $8$ llamado el **grupo de simetría del cuadrado**.

```

```{example}
Sea $C$ un conjunto no vacío y $\mathcal{A}(C)$ el conjunto de todas las biyecciones de $C$ en si mismo. Con la operación composición de funciones vista en la sección anterior, $\mathcal{A}(C)$ forma un grupo (no abeliano). En efecto, la composición de funciones biyectivas es asociativa, la identidad es una función biyectiva y toda biyección tiene una inversa. Los elementos de $\mathcal{A}(C)$ son llamados **permutaciones** y $\mathcal{A}(C)$ es llamado el grupo de permutaciones sobre $C$. Si $C=\{1,2, ..., n\}$, entonces $\mathcal{A}(C)$ es llamdo el **grupo simétrico sobre $n$ letras** y se denota $S_{n}$. Se puede ver que $|S_{n}|=n!$ (ejercicio \@ref(exr:ejc3)).

```

```{example, label="ejm1-21"}
Dados $G$ y $H$ dos grupos con identidades $e_{G}$ y $e_{H}$ respectivamente. Consideremos el producto cartesiano $G\times H$ y la operación binaria $(a,b)\ast (c,d)=(a\ast c,b\ast d)$ donde $a\ast c\in G$ y $b\ast d\in H$. Con esta operación $G\times H$ es un grupo con identidad $(e_{G}, e_{H})$ y con inverso $(a^{-1}, b^{-1})$ para cada elemento $(a,b)\in G\times H$.

```

### Ejercicios

```{exercise}
Sea $G$ un grupo y $C$ un conjunto no vacío. Sea $M(C,G)$ el conjunto de todas las funciones $f:C\longrightarrow G$. Definamos la operación de grupo como la suma de funciones, es decir, para cada $f,g\in M(C,G)$, $f\ast g = f +g$. Demuestre que $M(C,G)$ es un grupo, es abeliano si $G$ lo es.

```

```{exercise, label="ejc3"}
Demuestre que el grupo simétrico sobre $n$ letras es de orden $n!$.

```

```{exercise}
Demuestre que el grupo del ejemplo \@ref(exm: ejm1-21) es un grupo de orden $|G||H|$. Además muestre que $G\times H$ es un grupo abeliano si $G$ y $H$ lo son.

```

